# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'simple-asset-picker-example' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for simple-asset-picker-example
  pod 'SimpleAssetPicker', :path => '../../'
end
